name: Haskell CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GHC 9.4.8 using ghcup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        ghcup install 9.4.8
        ghcup set 9.4.8
      shell: bash

    - name: Install Cabal
      run: |
        cabal_version=3.4.0.0
        curl -LO "https://downloads.haskell.org/~cabal/cabal-install-${cabal_version}/cabal-install-${cabal_version}-x86_64-unknown-linux.tar.xz"
        tar -xf "cabal-install-${cabal_version}-x86_64-unknown-linux.tar.xz"
        mkdir -p ~/.cabal/bin
        mv cabal ~/.cabal/bin/
        cabal --version
        cabal update


    - name: Build project
      run: cabal build

    - name: Run tests
      run: cabal run app/Tests.hs -- $dictionaryInputFile $scoreInputFile
      env:
        dictionaryInputFile: "Dictionaries/01-Dictionary.txt"
        scoreInputFile: "Dictionaries/01-Scoring.txt"
