name: Haskell CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: 9.4.8
        cabal-version: 3.4.0.0

    - name: Build project
      run: cabal build

    - name: Run tests
      run: cabal run app/Tests.hs -- $dictionaryInputFile $scoreInputFile
      env:
        dictionaryInputFile: "Dictionaries/01-Dictionary.txt"
        scoreInputFile: "Dictionaries/01-Scoring.txt"
